In [ ]:
import numpy as np
a = np.arange(24).reshape(4,6)

In [ ]:
a

In [ ]:
a.flatten()

In [4]:
import tensorflow as tf
import matplotlib.pyplot as plt

In [ ]:
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()
plt.imshow(X_train[11], cmap='gray')

CNN feature extractor : 이미지는 위치 자체가 중요한 정보를 가지므로 column간 독립적이지 않다 -> 1-d로 그냥 바꾸면 공간에 대한 정보를 잃어버린다.
전통적 머신 러닝 방법에서는 PCA 등을 이용하여 차원을 낮추는 테크닉을 사용한다

이미지에서 feature는 로컬 또는 글로벌 정보를 말한다

89년에 만들어진 convolution 기법 - 전통적인 1차원 모델 - 신호처리에서 사용되던 기법

In [10]:
from scipy.signal import correlate, convolve

In [15]:
a = np.array([1,2,3])
b = np.array([-1,0,1])

In [17]:
# full 방식 1 2 3
#     -1 0 1        -> 1
#       -1 0 1      -> 2
#           ...
# same 원래 비교하는 자료 사이즈와 같은 사이즈로 나오게함
# valid 값이 하나만 나옴 => 내적과 계산방식이 같음
correlate(a,b, mode='valid')


array([2])

In [19]:
convolve(a,b, mode='full')
# 좌우 반전을 하고 correlation 연산하는 것

array([-1, -2, -2,  2,  3])

In [26]:
from scipy.signal import convolve2d, correlate2d

In [28]:
aa = np.arange(36).reshape(6,6)
bb = np.array([[1,0,1], [0,1,0], [1,0,1]])

In [29]:
correlate2d(aa, bb, mode='valid')

array([[ 35,  40,  45,  50],
       [ 65,  70,  75,  80],
       [ 95, 100, 105, 110],
       [125, 130, 135, 140]])

In [ ]:
# convolve2d()는 필터이다

In [ ]:
# 2차원 convolution은 가로, 세로 둘 다 반전한다.

translational invariance; 위치를 바꿔도 바뀌지 않는 특성
rotational invariance: 회전 시켜도 바뀌지 않는 특성
equivalance : 위치 빼고 나머지가 완전히 같음

convolution은 equivalance한 연산이다.
stationarity : 정상성, convolutional equivalant

독립성의 문제를 해결함. Convol을 통해서 특정 feature의 유무를 classification하는 문제로 변환함

https://transcranial.github.io/keras-js/#/

In [30]:
tf.keras.layers.Conv2D(32, 3)


input_ = tf.keras.Input(28,28)
x = tf.keras.layers.Dense(128, activation='relu')(input_)
x = tf.keras.layers.Dense(10, activation='relu')(x)

model = tf.keras.Model(input_, x)
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(28, 28)]                0         
                                                                 
 dense (Dense)               (28, 128)                 3712      
                                                                 
 dense_1 (Dense)             (28, 10)                  1290      
                                                                 
Total params: 5,002
Trainable params: 5,002
Non-trainable params: 0
_________________________________________________________________


In [32]:
#tf와 torch의 이미지 데이터는 기본적으로 3차원 데이터셋 width, height, color로 다룬다.

X_train = X_train[..., tf.newaxis]
input_ = tf.keras.Input((28,28,1))
x = tf.keras.layers.Conv2D(32,3, padding='same')(input_)
model = tf.keras.Model(input_, x)
model.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 28, 28, 1)]       0         
                                                                 
 conv2d_2 (Conv2D)           (None, 26, 26, 32)        320       
                                                                 
Total params: 320
Trainable params: 320
Non-trainable params: 0
_________________________________________________________________


In [5]:
import tensorflow as tf
print(tf.__version__)
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

2.10.0


[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 793084907379388164
 xla_global_id: -1]