In [1]:
import tensorflow as tf
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

In [2]:
tf.data.Dataset.from_tensors(X_train)

SyntaxError: invalid syntax (2573759257.py, line 1)

In [17]:
# b = tf.data.detaset
bb = tf.data.Dataset.from_tensor_slices((X_train, y_train))
path = 'dataset/images/'

In [18]:
im = tf.keras.preprocessing.image_dataset_from_directory(path, label_mode='categorical')

Found 1656 files belonging to 3 classes.


In [14]:
for i in im.take(1):
    print(i[1])

tf.Tensor(
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]], shape=(32, 3), dtype=float32)


In [19]:
idg = tf.keras.preprocessing.image.ImageDataGenerator()

In [21]:
dig = idg.flow_from_directory(path)

Found 1656 images belonging to 3 classes.


In [24]:
type(dig)

keras.preprocessing.image.DirectoryIterator

In [25]:
tf.data.Dataset.from_generator()

TypeError: DatasetV2.from_generator() missing 1 required positional argument: 'generator'

In [26]:
tf.keras.layers.experimental.preprocessing.PreprocessingLayer()

In [39]:
import pandas as pd

In [48]:
path_anno_air = 'dataset/annotations/airplane.csv'
airplane = pd.read_csv(path_anno_air, header=None)
face = pd.read_csv('dataset/annotations/face.csv', header=None)
motorcycle = pd.read_csv('dataset/annotations/motorcycle.csv', header=None)

In [49]:
head = {0:'fileName', 1:'x1', 2:'y1', 3:'x2', 4:'y2', 5:'target'}
airplane.rename(head, axis=1, inplace=True)
airplane['fileName'] = airplane.fileName.map(lambda n: 'airplane/'+n)
face.rename(head, axis=1, inplace=True)
face['fileName'] = airplane.fileName.map(lambda n: 'face/'+n)
motorcycle.rename(head, axis=1, inplace=True)
motorcycle['fileName'] = motorcycle.fileName.map(lambda n: 'motorcycle/'+n)

In [52]:
datasets = pd.concat([airplane, face, motorcycle], axis=0, ignore_index=True)
datasets.fileName = datasets.fileName.map(lambda n: 'dataset/images/'+n)
datasets

fileName  x1  y1   x2   y2      target
0       dataset/images/airplane/image_0001.jpg  49  30  349  137    airplane
1       dataset/images/airplane/image_0002.jpg  59  35  342  153    airplane
2       dataset/images/airplane/image_0003.jpg  47  36  331  135    airplane
3       dataset/images/airplane/image_0004.jpg  47  24  342  141    airplane
4       dataset/images/airplane/image_0005.jpg  48  18  339  146    airplane
...                                        ...  ..  ..  ...  ...         ...
2028  dataset/images/motorcycle/image_0794.jpg  47  44  218  133  motorcycle
2029  dataset/images/motorcycle/image_0795.jpg  44  38  216  135  motorcycle
2030  dataset/images/motorcycle/image_0796.jpg  47  40  217  141  motorcycle
2031  dataset/images/motorcycle/image_0797.jpg  48  54  211  150  motorcycle
2032  dataset/images/motorcycle/image_0798.jpg  42  33  218  140  motorcycle

[2033 rows x 6 columns]

In [61]:
idg = tf.keras.preprocessing.image.ImageDataGenerator()
dig = idg.flow_from_dataframe(datasets, x_col='fileName', y_col=['x1', 'y1', 'x2', 'y2', 'target'], class_mode='raw')
temp = next(dig)

Found 1217 validated image filenames.


C:\Users\tglkwon\AppData\Roaming\Python\Python310\site-packages\keras\preprocessing\image.py:1139: UserWarning: Found 816 invalid image filename(s) in x_col="fileName". These filename(s) will be ignored.
  warnings.warn(


In [62]:
temp[1]

array([[40, 7, 348, 138, 'airplane'],
       [38, 34, 228, 170, 'motorcycle'],
       [54, 24, 346, 110, 'airplane'],
       [52, 28, 347, 114, 'airplane'],
       [60, 26, 350, 107, 'airplane'],
       [60, 31, 353, 122, 'airplane'],
       [36, 14, 234, 146, 'motorcycle'],
       [38, 23, 232, 141, 'motorcycle'],
       [38, 15, 234, 116, 'motorcycle'],
       [58, 35, 358, 146, 'airplane'],
       [51, 32, 351, 140, 'airplane'],
       [60, 30, 356, 139, 'airplane'],
       [56, 33, 353, 105, 'airplane'],
       [46, 30, 344, 96, 'airplane'],
       [53, 27, 351, 114, 'airplane'],
       [56, 32, 352, 123, 'airplane'],
       [48, 25, 345, 125, 'airplane'],
       [61, 30, 353, 119, 'airplane'],
       [35, 22, 229, 123, 'motorcycle'],
       [33, 16, 231, 111, 'motorcycle'],
       [33, 38, 349, 118, 'airplane'],
       [57, 27, 355, 91, 'airplane'],
       [41, 29, 228, 135, 'motorcycle'],
       [66, 25, 349, 124, 'airplane'],
       [47, 33, 356, 93, 'airplane'],
       [66, 39,